routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('index');   // view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::middleware(['auth'])->group(function(){

	Route::resource('user', 'UsersController');
	Route::get('user/{id}/destroy', [
		'uses'	=>	'UsersController@destroy',
		'as'	=>	'user.destroy'
	]);

	Route::resource('roles', 'RolesController');
	Route::get('roles/{id}/destroy', [
		'uses'	=>	'RolesController@destroy',
		'as'	=>	'roles.destroy'
	]);

	//USUARIOS INACTIVO
//Administrador de la Aplicacion

//muesta los usuarios eliminados
	Route::get('/deshabilitado', [
		'uses'	=>	'UsersController@inactivo',
		'as'	=>	'user.inactivo'
	]);

	Route::get('{id}/habilitar',[
		'uses'	=> 'UsersController@habilitar',
		'as'	=>	'user.habilitar'
	]);

//Cambio de contraseña por parte del administrador
	Route::get('/{id}/password', [
		'uses'	=>	'UsersController@password',
		'as'	=>	'admin.password']);
	Route::post('/{id}/change/', [
        'uses'	=>	'UsersController@changepassword',
        'as'	=>	'admin.changepassword']);

//Cambiar de contraseña por parte del usuario
	Route::get('/changepassword/', [
		'uses'	=> 'UsersController@passwordchange',
		'as' 	=>	'user.password'
	]);
//guarda el cambio de contraseña
	Route::post('/updatepassword', [
		'uses'	=>	'UsersController@updatepassword',
		'as'	=>	'user.updatepassword'
	]);	

	Route::get('/seguridad', [
		'uses'	=>	'UsersController@seguridad',
		'as'	=>	'user.seguridad'
	]);

	Route::get('/bitacoras', [
		'uses'	=>	'BitacorasController@index',
		'as'	=>	'bitacoras.index'
	]);


	//Rutas asignados a los reportes que serán vistos
	//por el usuario estrategico

	Route::get('/prorrogas', [
		'uses'	=>	'ProrrogaController@ver',
		'as'	=>	'prorroga.ver'
	]);

	Route::post('prorrogas/filtro', [
		'uses'	=>	'ProrrogaController@prorroga',
		'as'	=>	'prorroga.filtro'
	]);

	Route::post('prorrogas/pdf', [
		'uses'	=>	'ProrrogaController@pdfProrroga',
		'as'	=>	'prorroga.pdfprorroga'
	]);

	Route::get('/visas', [
		'uses'	=>	'VisasController@ver',
		'as'	=>	'visas.ver'
	]);

	Route::post('visas/filtro', [
		'uses'	=>	'VisasController@visas',
		'as'	=>	'visas.filtro'

	]);

	Route::post('visas/pdfVisas', [
		'uses'	=>	'VisasController@pdfVisas',
		'as'	=>	'visas.pdfvisas'

	]);

	Route::get('/estadistica', [
		'uses'	=>	'ProrrogaController@verProrroga',
		'as'	=>	'prorroga.verprorroga'
	]);

	Route::post('estadistica/prorroga', [
		'uses'	=>	'ProrrogaController@estadisticaProrrogas',
		'as'	=>	'prorroga.estadistica'
	]);

	Route::post('estadistica/pdf', [
		'uses'	=>	'ProrrogaController@pdfEstadistica',
		'as'	=>	'prorroga.pdfestadistica'
	]);


	Route::get('/tramites', [
		'uses'	=>	'TramitesController@estadisticas',
		'as'	=>	'tramites.estadistica'
	]);

	Route::post('tramites/total', [
		'uses'	=>	'TramitesController@estadisticaTotal',
		'as'	=>	'tramites.total'
	]);

	Route::post('tramites/pdf', [
		'uses'	=> 	'TramitesController@tramitesPdf',
		'as'	=>	'tramites.pdf'
	]);

	Route::get('/estadisticas', [
		'uses'	=>	'VisasController@verEstadisticas',
		'as'	=>	'visas.vervisa'
	]);

	Route::post('estadistica/visas', [
		'uses'	=>	'VisasController@estadisticasVisas',
		'as'	=>	'visas.estadisticas'
	]);

	Route::post('estadisticas/pdf', [
		'uses'	=>	'VisasController@estadisticaPdf',
		'as'	=>	'visas.pdfestadistica'
	]);


//menus tacticos
	Route::get('visa/multiple/ver', [
		'uses'	=>	'VisasMultipleController@verVisaM',
		'as'	=>	'visas.multiple.ver'
	]);


	Route::post('multiple/visas/filtro',[
	'uses'=>'VisasMultipleController@visaMultiple',
	'as' => 'visas.multiple.no.residente'
	]);


	Route::get('ProrrogaHijo/ver',[
		'uses'  =>  'ProrrogaController@verProrrogaPTNAHPSyPTNAHPE',
		'as' 	=>	'prorroga.verPTNAHPSyPTNAHPE'
	]);


	Route::post('ProrrogaHijo/filtro',[
		'uses' 	=>	'ProrrogaController@prorrogaPTNAHPSyPTNAHPE',
		'as'	=>	'prorroga.PTNAHPSyPTNAHPE'
	]);

	Route::post('ProrrogaHijo/pdf',[
		'uses'	=>	'ProrrogaController@pdfprorrogaPTNAHPSyPTNAHPE',
		'as'	=>	'prorroga.pdfprorrogaPTNAHPSyPTNAHPE'
	]);

	Route::get('Especial/ingreso',[
		'uses'	=>	'PermisosController@verPerEspecialIngreso',
		'as'	=>	'permiso.verEspecialIngreso'
	]);

	Route::post('Especial/filtro',[
		'uses'	=>	'PermisosController@PerEspecialIngreso',
		'as'	=>	'permiso.especialIngreso'
	]);

	Route::post('Especial/pdf',[
		'uses'	=>	'PermisosController@pdfPerEspecialIngreso',
		'as'	=>	'permiso.pdf'
	]);

	Route::post('visa/multiple/pdf', [
		'uses'	=>	'VisasMultipleController@pdfVisasMultiple',
		'as'	=>	'visas.pdf.no.residente'
	]);


	Route::get('visa/multiple/inversionista/ver', [
		'uses'	=>	'VisasMultipleController@verVisaMulInver',
		'as'	=>	'visas.multiple.inversionista.ver'
	]);


	Route::post('multiple/visas/inver/filtro',[
	'uses'	=>	'VisasMultipleController@visaMultipleInversionista',
	'as' 	=> 	'visas.multiple.inversionista'
	]);

	Route::post('visa/multiple/inver/pdf', [
		'uses'	=>	'VisasMultipleController@pdfVisasMultipleInversionista',
		'as'	=>	'visas.mult.inversionista.pdf'
	]);

	Route::get('Especial/inversionista',[
		'uses'	=>	'PermisosController@verPerEspecialInver',
		'as' 	=>	'permisos.verInversionista'
	]);

	Route::post('Especial/filtro/inver',[
		'uses'	=>	'PermisosController@PerEspecialInver',
		'as'	=>	'permisos.inversion'
	]);

	Route::post('Especial/pdf/inver',[
		'uses'	=>	'PermisosController@pdfPerEspecialInver',
		'as'	=>	'permisos.inver.pdf'
	]);

	Route::get('Especial/marinos',[
		'uses'	=>	'PermisosController@verPerEspecialMarino',
		'as' 	=>	'permisos.marinos'
	]);

	Route::post('Especial/filtro/marino',[
		'uses'	=>	'PermisosController@perEspecialMarino',
		'as'	=>	'permisos.marinosFiltro'
	]);

	Route::post('Especial/pdf/marino',[
		'uses'	=>	'PermisosController@pdfPerEspecialMarino',
		'as'	=>	'permisos.marinos.pdf'
	]);

});

resources/views/rol/create.blade.php
@extends('layouts.template')
@section('content')
<div class="container">
  <div class="row">
    <div class="col-md-12 col-md-offset-1" align="center">
      <div class="panel panel-default">
        <div class="panel-heading"><h2 style="padding-top: 2%">Crear Roles</h2></div>
          <div class="panel-body">

        	<form action="{{ route('roles.store') }}" method="post" role="form" class="contactForm">
    {{csrf_field()}}
              <div class="form-group">
                            <div class="col-md-6">
                                <input id="nombre" type="text" class="form-control" name="nombre" required autofocus placeholder="Nombre" placeholder="Nombre">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-md-6">
                                <input id="display_nombre" type="text" class="form-control" name="display_nombre" required autofocus placeholder="Slug">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-md-6">
                              <textarea rows="4" cols="10" name="descripcion" id="descripcion" class="form-control" required></textarea>
                             
                            </div>
                        </div>

                  <div align="center">
                    <h3>Permiso Especial</h3>
                  </div>


                  <div class="col-md-12 form-group">
                    
                    <select class="col-md-6 form-group" name="permiso_especial">
                      <option>Seleccionar Permiso Especial</option>
                    <option value="all-access">Acceso Total</option>
                    <option value="no-access">No acceso</option>
                    </select>
                  </div>


                <div class="form-group" align="center">
                <h3>Asignar Privilegios</h3>
                </div>
                <div style="overflow: scroll; height: 200px">
                  <div class="col-md-7 form-group" align="left">
                    <ul>
                      @foreach ($permisos as $permisos)
                    
                          <label>
                            <input  type="checkbox" value="{{$permisos->id }}" name="permisos[]">
                                         <strong>{{$permisos->name}}</strong><em>({{$permisos->description ?: 'Sin descripción'}})</em>
                            </label>
                          
                          @endforeach

                  </ul>
                  </div>
                </div>

                  <div class="text-center col-md-12" style="padding-top: 3%;padding-bottom: 2%">
                    <button class="btn btn-primary" type="submit">Guardar</button>
                     <a href="{{route('roles.index')}}" class="btn btn-secondary" style="float:right 5%;"> <span>
                            <b>Cancelar</b></span></a>
                  </div>
                </div>
              </div>
            </form>
        </div>
              
@endsection

resources/views/rol/edit.blade.php
@extends('layouts.template')
@section('content')
<div class="container">
  <div class="row">
    <div class="col-md-12 col-md-offset-1" align="center">
      <div class="panel panel-default">
        <div class="panel-heading"><h2 style="padding-top: 2%">Editar Roles</h2></div>
        <div class="panel-body">
          <form class="form-horizontal" method="POST" action="{{route('roles.update', $roles->id )}}">
            {{ csrf_field() }}
            {{ method_field('PUT') }}
            <div class="form-group">
                <div class="col-md-6">
                  <label for="name" class="col-md-4 control-label">Nombre</label>
                     <input id="nombre" type="text" class="form-control" name="nombre" required autofocus value="{{ $roles->name}}" placeholder="Nombre">
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-6">
                  <label for="name" class="col-md-4 control-label">userName</label>
                     <input id="display_nombre" type="text" class="form-control" name="display_nombre" required autofocus value="{{ $roles->slug}}">
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-6">
                  <label for="name" class="col-md-4 control-label">Descripción</label>
                     <textarea rows="4" cols="10" name="descripcion" id="descripcion" class="form-control" required>{{ $roles->description }}</textarea>     
                </div>
            </div>
            <div align="center">
                <h3>Permiso Especial</h3>
            </div>
            <div class="col-md-12 form-group">        
                      <select name="permiso_especial" class="span4 form-group">
                        <option @if(old('permiso_especial', $roles->special)== null) selected @endif>Selecciona Permiso Especial</option>
                        <option @if(old('permiso_especial', $roles->special)=='all-access') selected @endif>Acceso Total</option>
                        <option @if(old('permiso_especial', $roles->special)=='no-access') selected @endif>No acesso</option>
                      </select>
            </div>
            <div class="form-group" align="center">
                <h3>Asignar Privilegios</h3>
            </div>
            <div style="overflow: scroll; height: 300px;" >
               <div class="col-md-8 form-group" align="left">
                <ul>
                    @foreach($permisos as $permisos)
                      <label>
                        <input type="checkbox" value="{{$permisos->id}}"                        {{in_array($permisos->id, $permission) ? "checked" : null}} name="permissions[]">
                            {{$permisos->name}}</strong><em>({{$permisos->description ?: 'Sin descripción'}})</em>
                      </label>    
                    @endforeach
                </ul>
              </div>
            </div>
            <div class="text-center col-md-12 " style="padding-top: 3%;padding-bottom: 2%">
               <button class="btn btn-primary" type="submit">Guardar</button>
                  <a href="{{route('roles.index')}}" class="btn btn-secondary" style="float:right 5%;"> <span>
                            <b>Cancelar</b></span></a>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
@endsection

resources/views/rol/index.blade.php
@extends('layouts.template')
@section('content')
<div class="container" style="margin-top: 3%">
        <div class="col-md-12 col-md-offset-1">
            <div class="table-title" style=" margin-bottom: 1%">
                <div class="row">
                    <div class="col-md-12">

                        <h1 align="center">Gestion de Usuarios</h1>
                        <div style="padding-left: 70%">
                        
                        <a href="{{ route('roles.create') }}" class="btn btn-primary"> <span>
                            <b>Crear Roles</b></span></a></div>
                             
                    </div>
                </div>
            </div>
            <table class="table table-striped table-hover" id="myTable" style="background: #fff;width: 100%">
                <thead>
                <tr>
                   
                    <th>Rol</th>
                    <th> Slug</th>
                    <th>Descripcion </th>
                    
                    <th width="23%">Acciones</th>
                </tr>
                </thead>
                <tbody>
                    @foreach($rol as $rol)
                <tr>
                    <td>{{ $rol->name }}</td>
                    <td>{{ $rol->slug}}</td>
                    <td>{{ $rol->description }}</td>
                   
                        <td>
                    
                        <a href="{{ route('roles.edit', $rol->id) }}" class="btn btn-warning"><span class="ion-edit" style="color: white"></span> </a>
                    
                    
                        <a class="btn btn-danger" onclick="eliminar('{{ $rol->id }}')"><span class="ion-trash-a" style="color: white"></span>
                    </a>
                    
                      </td>
                </tr>
                @endforeach
                </tbody>
            </table>
<!--Modal-->
            <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
              <div class="modal-dialog" role="document">
                <div class="modal-content">
                  <div class="modal-body">
                    <p> ¿Desea Eliminar? </p>
                    <input type="hidden">
                  </div>
                  <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                    <a class="btn btn-danger" id="aceptar" style="color: white">Sí</a>
                  </div>
                </div>
              </div>
            </div>
        </div>
    </div>
@endsection
@section('js')
<script>
    
    function eliminar(id){
        var iddentified=id;
        
        $('#exampleModal').modal();
        document.getElementById("aceptar").addEventListener("click", function() {
        var url ='{{ route("roles.destroy", ":id") }}';
        url=url.replace(":id",iddentified);
        window.location.href=url;
        }, false);

    }
    </script>
@endsection