routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('index');   // view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::middleware(['auth'])->group(function(){

	Route::resource('user', 'UsersController');
	Route::get('user/{id}/destroy', [
		'uses'	=>	'UsersController@destroy',
		'as'	=>	'user.destroy'
	]);

	Route::resource('roles', 'RolesController');
	Route::get('roles/{id}/destroy', [
		'uses'	=>	'RolesController@destroy',
		'as'	=>	'roles.destroy'
	]);

	//USUARIOS INACTIVO
//Administrador de la Aplicacion

//muesta los usuarios eliminados
	Route::get('/deshabilitado', [
		'uses'	=>	'UsersController@inactivo',
		'as'	=>	'user.inactivo'
	]);

	Route::get('{id}/habilitar',[
		'uses'	=> 'UsersController@habilitar',
		'as'	=>	'user.habilitar'
	]);

//Cambio de contraseña por parte del administrador
	Route::get('/{id}/password', [
		'uses'	=>	'UsersController@password',
		'as'	=>	'admin.password']);
	Route::post('/{id}/change/', [
        'uses'	=>	'UsersController@changepassword',
        'as'	=>	'admin.changepassword']);

//Cambiar de contraseña por parte del usuario
	Route::get('/changepassword/', [
		'uses'	=> 'UsersController@passwordchange',
		'as' 	=>	'user.password'
	]);
//guarda el cambio de contraseña
	Route::post('/updatepassword', [
		'uses'	=>	'UsersController@updatepassword',
		'as'	=>	'user.updatepassword'
	]);	

	Route::get('/seguridad', [
		'uses'	=>	'UsersController@seguridad',
		'as'	=>	'user.seguridad'
	]);

	Route::get('/bitacoras', [
		'uses'	=>	'BitacorasController@index',
		'as'	=>	'bitacoras.index'
	]);


	//Rutas asignados a los reportes que serán vistos
	//por el usuario estrategico

	Route::get('/prorrogas', [
		'uses'	=>	'ProrrogaController@ver',
		'as'	=>	'prorroga.ver'
	]);

	Route::post('prorrogas/filtro', [
		'uses'	=>	'ProrrogaController@prorroga',
		'as'	=>	'prorroga.filtro'
	]);

	Route::post('prorrogas/pdf', [
		'uses'	=>	'ProrrogaController@pdfProrroga',
		'as'	=>	'prorroga.pdfprorroga'
	]);

	Route::get('/visas', [
		'uses'	=>	'VisasController@ver',
		'as'	=>	'visas.ver'
	]);

	Route::post('visas/filtro', [
		'uses'	=>	'VisasController@visas',
		'as'	=>	'visas.filtro'

	]);

	Route::post('visas/pdfVisas', [
		'uses'	=>	'VisasController@pdfVisas',
		'as'	=>	'visas.pdfvisas'

	]);

	Route::get('/estadistica', [
		'uses'	=>	'ProrrogaController@verProrroga',
		'as'	=>	'prorroga.verprorroga'
	]);

	Route::post('estadistica/prorroga', [
		'uses'	=>	'ProrrogaController@estadisticaProrrogas',
		'as'	=>	'prorroga.estadistica'
	]);

	Route::post('estadistica/pdf', [
		'uses'	=>	'ProrrogaController@pdfEstadistica',
		'as'	=>	'prorroga.pdfestadistica'
	]);


	Route::get('/tramites', [
		'uses'	=>	'TramitesController@estadisticas',
		'as'	=>	'tramites.estadistica'
	]);

	Route::post('tramites/total', [
		'uses'	=>	'TramitesController@estadisticaTotal',
		'as'	=>	'tramites.total'
	]);

	Route::post('tramites/pdf', [
		'uses'	=> 	'TramitesController@tramitesPdf',
		'as'	=>	'tramites.pdf'
	]);

	Route::get('/estadisticas', [
		'uses'	=>	'VisasController@verEstadisticas',
		'as'	=>	'visas.vervisa'
	]);

	Route::post('estadistica/visas', [
		'uses'	=>	'VisasController@estadisticasVisas',
		'as'	=>	'visas.estadisticas'
	]);

	Route::post('estadisticas/pdf', [
		'uses'	=>	'VisasController@estadisticaPdf',
		'as'	=>	'visas.pdfestadistica'
	]);


//menus tacticos
	Route::get('visa/multiple/ver', [
		'uses'	=>	'VisasMultipleController@verVisaM',
		'as'	=>	'visas.multiple.ver'
	]);


	Route::post('multiple/visas/filtro',[
	'uses'=>'VisasMultipleController@visaMultiple',
	'as' => 'visas.multiple.no.residente'
	]);


	Route::get('ProrrogaHijo/ver',[
		'uses'  =>  'ProrrogaController@verProrrogaPTNAHPSyPTNAHPE',
		'as' 	=>	'prorroga.verPTNAHPSyPTNAHPE'
	]);


	Route::post('ProrrogaHijo/filtro',[
		'uses' 	=>	'ProrrogaController@prorrogaPTNAHPSyPTNAHPE',
		'as'	=>	'prorroga.PTNAHPSyPTNAHPE'
	]);

	Route::post('ProrrogaHijo/pdf',[
		'uses'	=>	'ProrrogaController@pdfprorrogaPTNAHPSyPTNAHPE',
		'as'	=>	'prorroga.pdfprorrogaPTNAHPSyPTNAHPE'
	]);

	Route::get('Especial/ingreso',[
		'uses'	=>	'PermisosController@verPerEspecialIngreso',
		'as'	=>	'permiso.verEspecialIngreso'
	]);

	Route::post('Especial/filtro',[
		'uses'	=>	'PermisosController@PerEspecialIngreso',
		'as'	=>	'permiso.especialIngreso'
	]);

	Route::post('Especial/pdf',[
		'uses'	=>	'PermisosController@pdfPerEspecialIngreso',
		'as'	=>	'permiso.pdf'
	]);

	Route::post('visa/multiple/pdf', [
		'uses'	=>	'VisasMultipleController@pdfVisasMultiple',
		'as'	=>	'visas.pdf.no.residente'
	]);


	Route::get('visa/multiple/inversionista/ver', [
		'uses'	=>	'VisasMultipleController@verVisaMulInver',
		'as'	=>	'visas.multiple.inversionista.ver'
	]);


	Route::post('multiple/visas/inver/filtro',[
	'uses'	=>	'VisasMultipleController@visaMultipleInversionista',
	'as' 	=> 	'visas.multiple.inversionista'
	]);

	Route::post('visa/multiple/inver/pdf', [
		'uses'	=>	'VisasMultipleController@pdfVisasMultipleInversionista',
		'as'	=>	'visas.mult.inversionista.pdf'
	]);

	Route::get('Especial/inversionista',[
		'uses'	=>	'PermisosController@verPerEspecialInver',
		'as' 	=>	'permisos.verInversionista'
	]);

	Route::post('Especial/filtro/inver',[
		'uses'	=>	'PermisosController@PerEspecialInver',
		'as'	=>	'permisos.inversion'
	]);

	Route::post('Especial/pdf/inver',[
		'uses'	=>	'PermisosController@pdfPerEspecialInver',
		'as'	=>	'permisos.inver.pdf'
	]);

	Route::get('Especial/marinos',[
		'uses'	=>	'PermisosController@verPerEspecialMarino',
		'as' 	=>	'permisos.marinos'
	]);

	Route::post('Especial/filtro/marino',[
		'uses'	=>	'PermisosController@perEspecialMarino',
		'as'	=>	'permisos.marinosFiltro'
	]);

	Route::post('Especial/pdf/marino',[
		'uses'	=>	'PermisosController@pdfPerEspecialMarino',
		'as'	=>	'permisos.marinos.pdf'
	]);

});

app/User.php
<?php

namespace App;

use Caffeinated\Shinobi\Traits\ShinobiTrait;
use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Database\Eloquent\SoftDeletes;

class User extends Authenticatable
{
    use Notifiable;
    use ShinobiTrait { restore as private restoreA; }
    use SoftDeletes { restore as private restoreB; }

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
       public function restore()
    {
        $this->restoreA();
        $this->restoreB();
    }

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
       'nombre','apellido', 'username', 'email', 'password',
    ];

    public $timestamps=true;
    protected $dates = ['deleted_at'];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];


    public function bitacoras(){

        return $this->hasMany('App\Bitacora');
    }
}

app/Http/Controllers/UsersController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\User;
use Caffeinated\Shinobi\Models\Role;
use Validator;
use Auth;
use Hash;
use Laracasts\Flash\Flash;

class UsersController extends Controller
{
    //

    public function __construct(){

        $this->middleware('permission:menu-administrador')->only(['index', 'seguridad']);
        $this->middleware('permission:user-edit')->only(['edit', 'update']);
        $this->middleware('permission:user-delete')->only('destroy');
        $this->middleware('permission:user-inactivo')->only('inactivo');
        $this->middleware('permission:user-habilitar')->only('habilitar');
        $this->middleware('permission:admin-password')->only(['password', 'changepassword']);
               
    }


    public function index(){

    	$user = User::orderBy('id', 'DESC')->get();
        $id = Auth::id();
    	return view('user.index')->with('user', $user)->with('id', $id);

    }

   public function edit($id){


   		$roles = Role::get();
    	$user = User::find($id);
        $rol= $user->roles->pluck('id')->ToArray();
        //dd($rol);


    	return view('user.edit', compact('user', 'roles', 'rol'));
    }

    public function update(Request $request, $id){
          $this->validate($request, [
            'nombre'  => 'required',
            'apellido'  => 'required',
            'usuario' => 'required|max:255',
            'roles'    => 'required'
        ]);

    	//actualiza primero al usuario
    	//segundo se actualiza al rol

    	//actualiza el usuario
    	$user = User::find($id);
    	$user->nombre = $request->nombre;
    	$user->apellido = $request->apellido;
    	$user->username = $request->usuario;
    	$user->update();

    	//actualizar role
    	$user->roles()->sync($request->get('roles'));
        flash("¡Se ha editado el usuario " . $user->username . " de forma exitosa")->warning()->important();
    	return redirect()->route('user.index');
    }

    public function show($id){

    	$user = User::find($id);

        $roles = Role::join("role_user","role_user.role_id","=","roles.id")
            ->where("role_user.user_id",$id)
            ->get();

    	return view('user.show', compact('user', 'roles'));
    }

    public function destroy($id){

		$user = User::find($id);
		$user->delete();
        flash("¡Se ha eliminado el usuario " . $user->username . " de forma exitosa")->error()->important();
		return redirect()->route('user.index');

    }


    public function inactivo(Request $request){

         $id = Auth::id();
        $users = User::onlyTrashed()->get();
        return view('user.inactivo')->with('users', $users)->with('id', $id);

    }

    public function habilitar($id){

        $user = User::onlyTrashed()->where('id', $id)->restore();
        $user = User::find($id);
        return redirect()->route('user.index');
    }


    public function password($id){

        $user = User::find($id);
        return view('user.password')->with('user', $user);
    }

    public function changepassword(Request $request, $id){
         $this->validate($request, [
            'contraseña'           => 'required|string|min:8',
            'confirmar_contraseña' => 'required|same:contraseña|min:8',
        ]);

        $user = User::find($id);
         //dd($user);
        $user->password = bcrypt($request->contraseña);
        $user->save();
        flash("¡Se ha editado la contraseña " . $user->name . " de forma exitosa")->warning()->important();
        return redirect()->route('user.seguridad');

    }

    public function passwordchange(){

        return view('user.newpassword');
    }


    public function updatepassword(Request $request){
         $this->validate($request, [
            'contraseña_actual'             => 'required',
            'contraseña_nueva'              => 'required|string|min:8',
            'confirmar_contraseña'          => 'required|same:contraseña_nueva|min:8',
        ]);

        if (Hash::check($request->contraseña_actual, Auth::user()->password)){
        $user = new User;
        $user->where('email', '=', Auth::user()->email)
             ->update(['password' => bcrypt($request->contraseña_nueva)]);
        flash("La contraseña ha sido selecionada exitosamente")->success()->important();
        return redirect()->route('home');
        
        }
    else
        {
        
        //return redirect('users.password');
       flash('¡ERROR! ¡La contraseña ingresada no coincide con nuestros datos!')->error()->important();
        return back()->withInput();
        }

		}

	public function seguridad(){

		$user = User::orderBy('id', 'DESC')->get();
		
        $id = Auth::id();
    	return view('user.seguridad')->with('user', $user)->with('id', $id);
	}
}

resources/views/user/edit.blade.php
@extends('layouts.template')
@section('content')

<div class="container">

  <!-- Despliega mensajes de error -->
                        @if (count($errors) > 0)
                            <div class="alert alert-danger">
                              <button type="button" class="close" data-dismiss="alert">
                                &times;</button>
                                <strong>¡ERROR!</strong> Hay errores en la información ingresada.<br><br>
                                <ul>
                                    @foreach ($errors->all() as $error)
                                        <li>{{ $error }}</li>
                                    @endforeach
                                </ul>
                            </div>
@endif
  <div class="row">
    <div class="col-md-12 col-md-offset-1" align="center">
<h1 style="padding-top: 2%">Editar Usuario</h1>
  <form action="{{ route('user.update', $user->id) }}" method="post" role="form" class="contactForm">
    {{csrf_field()}}
    {{ method_field('PUT') }}
              
                <div class="form-group">
                             <label for="name" class="col-md-4 control-label">Nombre</label>
                            <div class="col-md-6 {{ $errors->has('nombre') ?  ' has-error' : '' }}">
                                <input id="nombre" type="text" class="form-control" name="nombre" value="{{ $user->nombre}}" required autofocus placeholder="Nombre">

                            </div>
                            <div class="validation">
                    @if ($errors->has('nombre'))
                                        <span class="help-block">
                                        <strong>{{ $errors->first('nombre') }}</strong>
                                    </span>
                    @endif
                  </div>
                  </div>
                  <div class="form-group">
                             <label for="name" class="col-md-4 control-label">Apellido</label>
                            <div class="col-md-6 {{  $errors->has('apellido') ? ' has-error' : '' }}">
                                <input id="apellido" type="text" class="form-control" name="apellido" value="{{ $user->apellido }}" required autofocus placeholder="Nombre">

                            </div>
                            <div class="validation">
                    @if ($errors->has('apellido'))
                                        <span class="help-block">
                                        <strong>{{ $errors->first('apellido') }}</strong>
                                    </span>
                    @endif
                  </div>
                  </div>
                  <div class="form-group">
                             <label for="usuario" class="col-md-4 control-label">Nombre de Usuario</label>
                            <div class="col-md-6 {{  $errors->has('usuario') ? ' has-error' : '' }}">
                                <input id="usuario" type="text" class="form-control" name="usuario" value="{{ $user->username }}" required autofocus placeholder="Nombre">

                            </div>

                            <div class="validation">
                    @if ($errors->has('usuario'))
                                        <span class="help-block">
                                        <strong>{{ $errors->first('usuario') }}</strong>
                                    </span>
                    @endif
                  </div>
                  </div>
            <div class="col-md-8 form-group">
              <hr>
              <h3>Lista de Roles</h3>
                </div>
          <div class="col-md-7 form-group {  $errors->has('roles') ? ' has-error' : '' }}" align="left">
            <ul>
              @foreach ($roles as $role)
            
                  <label>
                              <input type="checkbox" value="{{$role->id}}"
                                               {{in_array($role->id, $rol) ? "checked" : null}} name="roles[]">
                                          {{$role->name}}</strong><em>({{$role->description ?: 'Sin descripción'}})</em>
                            </label>    
                  
                  @endforeach

          </ul>
          <div class="validation">
                    @if ($errors->has('roles'))
                                        <span class="help-block">
                                        <strong>{{ $errors->first('roles') }}</strong>
                                    </span>
                    @endif
                  </div>
          </div>
                  <div class="span8 form-group">
                    <button class="btn btn-primary" type="submit">Guardar</button>
                     <a href="{{route('user.index')}}" class="btn btn-secondary" style="float:right 5%;"> <span>
                            <b>Cancelar</b></span></a>
                  </div>
              
              
            </form>
        </div>
       </div>
       </div>       
@endsection

resources/views/user/inactivo.blade.php
@extends('layouts.template')
@section('content')

<div class="container" style="margin-top: 3%">
        <div class="col-md-12 col-md-offset-1">
            <div class="table-title" style=" margin-bottom: 1%">
                <div class="row">
                    <div class="col-md-12">
                        <h1 align="center">Gestion de Usuarios Inactivos</h1>
                    </div>
                      
                </div>
            </div>
            <table class="table table-striped table-hover" id="myTable" style="background: #fff;width: 100%">
                <thead>
                <tr>
                    <th>N°</td>
                    <th>Nombre Completo</th>
                    <th>Nombre de Usuario</th>
                    
                    <th width="23%">Acciones</th>
                </tr>
                </thead>
                <tbody>
                    @foreach($users as $user)
                <tr>
                    <td>{{ $user->id }}</td>
                    <td>{{ $user->nombre}} {{ $user->apellido }}</td>
                    <td>{{ $user->username }}</td>
                    <td>
                    @can('user-habilitar')
                <a style="margin-right: 3%" class="btn btn-primary" onclick="eliminar('{{ $user->id }}')">
                    <span class="ion-android-unlock" style="color: white"></span></a>
                    @endcan   
                    </td> 
                </tr>
                @endforeach
                </tbody>
            </table>
         <!--Modal-->
            <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
              <div class="modal-dialog" role="document">
                <div class="modal-content">
                  <div class="modal-body">
                    <p> ¿Desea Habilitar? </p>
                    <input type="hidden">
                  </div>
                  <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                    <a class="btn btn-primary" id="aceptar" style="color: white">Sí</a>
                  </div>
                </div>
              </div>
            </div>
        </div>
    </div>
@endsection
@section('js')
<script>
    
    function eliminar(id){
        var iddentified=id;
        
        $('#exampleModal').modal();
        document.getElementById("aceptar").addEventListener("click", function() {
        var url ='{{ route("user.habilitar", ":id") }}';
        url=url.replace(":id",iddentified);
        window.location.href=url;
        }, false);

    }
    </script>
@endsection

resources/views/user/index.blade.php
@extends('layouts.template')
@section('content')
<div class="container" style="margin-top: 3%">
        <div class="col-md-12 col-md-offset-1">
            <div class="table-title" style=" margin-bottom: 1%">
                <div class="row">
                    <div class="col-md-12">

                        <h1 align="center">Gestion de Usuarios</h1>
                        <div style="padding-left: 70%">
                            @can('user-inactivo')
                        <a href="{{ route('user.inactivo') }}" class="btn btn-primary"> <span>
                            @endcan
                            <b>Usuarios Inactivos</b></span></a></div>
                    </div>
                </div>
            </div>
            <table class="table table-striped table-hover" id="myTable" style="background: #fff;width: 100%">
                <thead>
                <tr>
                    <th>N°</td>
                    <th>Nombre Completo</th>
                    <th> Nombre de Usuario</th>
                    
                    <th width="23%">Acciones</th>
                </tr>
                </thead>
                <tbody>
                    @foreach($user as $user)
                <tr>
                    <td>{{ $user->id }}</td>
                    <td>{{ $user->nombre}} {{ $user->apellido }}</td>
                    <td>{{ $user->username }}</td>
                   
                        <td>
                    @can('user-edit')
                        <a href="{{ route('user.edit', $user->id) }}" class="btn btn-warning"><span class="ion-edit" style="color: white"></span> </a>
                    @endcan
                   
                        @if($user->id != $id)
                     @can('user-delete')
                        <a class="btn btn-danger" onclick="eliminar('{{ $user->id }}')"><span class="ion-trash-a" style="color: white"></span>
                    </a>
                    @endcan
                    @endif
                   
                      </td>
                </tr>
                @endforeach
                </tbody>
            </table>
<!--Modal-->
            <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
              <div class="modal-dialog" role="document">
                <div class="modal-content">
                  <div class="modal-body">
                    <p> ¿Desea Eliminar? </p>
                    <input type="hidden">
                  </div>
                  <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                    <a class="btn btn-danger" id="aceptar" style="color: white">Sí</a>
                  </div>
                </div>
              </div>
            </div>
        </div>
    </div>
@endsection
@section('js')
<script>
    
    function eliminar(id){
        var iddentified=id;
        
        $('#exampleModal').modal();
        document.getElementById("aceptar").addEventListener("click", function() {
        var url ='{{ route("user.destroy", ":id") }}';
        url=url.replace(":id",iddentified);
        window.location.href=url;
        }, false);

    }
    </script>
@endsection

resources/views/user/newpassword.blade.php
@extends('layouts.template')
@section('content')
<div class="container">
       <!-- Despliega mensajes de error -->
                        @if (count($errors) > 0)
                            <div class="alert alert-danger">
                              <button type="button" class="close" data-dismiss="alert">
                                &times;</button>
                                <strong>¡ERROR!</strong> Hay errores en la información ingresada.<br><br>
                                <ul>
                                    @foreach ($errors->all() as $error)
                                        <li>{{ $error }}</li>
                                    @endforeach
                                </ul>
                            </div>
@endif
  <div class="row">
    <div class="col-md-12 col-md-offset-1" align="center">
      <h1 style="padding-top: 2%">Cambiar Contraseña</h1>
      <form action="{{ route('user.updatepassword') }}" method="post" role="form" class="contactForm">
        {{csrf_field()}}
         <div class="form-group">
                            <div class="col-md-6 {{  errors->has('contraseña_actual') ? ' has-error' : '' }}">
                                <input id="contraseña_actual" type="password" class="form-control" name="contraseña_actual" required placeholder="Contraseña Actual">

                            </div>
                             <div class="validation">
                    @if ($errors->has('contraseña_actual'))
                                        <span class="help-block">
                                        <strong>{{ $errors->first('contraseña_actual') }}</strong>
                                    </span>
                    @endif
                  </div>
                          </div>
                            <div class="form-group ">
                            <div class="col-md-6 {{  errors->has('contraseña_nueva') ? ' has-error' : '' }}">
                                <input id="contraseña_nueva" type="password" class="form-control" name="contraseña_nueva" required placeholder="Contraseña Nueva">

                            </div>
                             <div class="validation">
                    @if ($errors->has('contraseña_nueva'))
                                        <span class="help-block">
                                        <strong>{{ $errors->first('contraseña_nueva') }}</strong>
                                    </span>
                    @endif
                  </div>
                          </div>
                            <div class="form-group">
                            <div class="col-md-6 {{  errors->has('confirmar_contraseña') ? ' has-error' : '' }}">
                                <input id="confirmar_contraseña" type="password" class="form-control" name="confirmar_contraseña" required placeholder="Confirmar Contraseña">

                            </div>
                            <div class="validation">
                    @if ($errors->has('confirmar_contraseña'))
                                        <span class="help-block">
                                        <strong>{{ $errors->first('confirmar_contraseña') }}</strong>
                                    </span>
                    @endif
                  </div>
                            </div>
                            <div class="col-md-12 form-group">
                  <div class="text-center">
                    <button class="btn btn-primary" type="submit">Cambiar Contraseña</button>
                    <a href="{{ route('home') }}" class="btn btn-secondary" style="float:right 5%;"> <span>
                            <b>Cancelar</b></span></a>
                  </div>
                </div>
      </form>
    </div>
  </div>
</div>
@endsection

resources/views/user/seguridad.blade.php
@extends('layouts.template')
@section('content')
<div class="container" style="margin-top: 3%">
        <div class="col-md-12 col-md-offset-1">
            <div class="table-title" style=" margin-bottom: 1%">
                <div class="row">
                    <div class="col-md-12">

                        <h1 align="center">Seguridad y Roles</h1>
                        <div style="padding-left: 50%">
                        <a href="{{ route('roles.index') }}" class="btn btn-primary"> <span>
                            <b>Gestion de Roles</b></span></a>
                             <a href="{{ route('bitacoras.index') }}" class="btn btn-primary"> <span>
                            <b>Bitacoras</b></span></a></div>
                     </div>

                </div>
            </div>
            <table class="table table-striped table-hover" id="myTable" style="background: #fff;width: 100%">
                <thead>
                <tr>
                    <th>N°</td>
                    <th>Nombre Completo</th>
                    <th> Nombre de Usuario</th>
                    <th> Roles</th>
                    
                    <th width="23%">Acciones</th>
                </tr>
                </thead>
                <tbody>
                    @foreach($user as $user)
                <tr>
                    <td>{{ $user->id }}</td>
                    <td>{{ $user->nombre}} {{ $user->apellido }}</td>
                    <td>{{ $user->username }}</td>
                   <td> <ul>
                    @foreach($user->roles as $rol)
                        <li>
                            {{$rol->name}}
                        </li>
                      @endforeach
                    </ul>
                </td>
                  <td>
                    @if($user->id != $id)
               
                <a href="{{ route('admin.password', $user->id) }}"  class="btn btn-info"><span class="ion-key"></span></a>
                
                    @endif
                    
                      </td>
                </tr>
                @endforeach
                </tbody>
            </table>

            
        </div>
    </div>
@endsection